# Generated by Django 4.2.5 on 2023-09-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_data2', models.FloatField(default=0)),
                ('DO_data2', models.FloatField(default=0)),
                ('EC_data2', models.FloatField(default=0)),
            ],
        ),
    ]
