# Generated by Django 4.2.5 on 2023-09-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0002_co2_delete_my_apps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CO2',
            new_name='my_apps',
        ),
    ]
